[package]
name = "vk-rs"
version = "0.1.0"
authors = ["LoST_ <atilkurtulmus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["windef", "winuser", "libloaderapi"] }

[[bin]]
name = "vk-rs"
path = "main.rs"
