[package]
name = "vk-rs"
version = "0.1.1"
authors = ["LoST_ <atilkurtulmus@gmail.com>"]
edition = "2018"
build = "src/build.rs"
description = "vulkan wrapper"
license = "MIT"
repository = "https://github.com/atkurtul/vk-rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "vk_rs"
path = "src/lib.rs"

[[example]]
name = "example"
path = "examples/main.rs"

[dev-dependencies]
winapi = { version = "0.3.9", features = ["windef", "winuser", "libloaderapi"] }

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }